use_frameworks!

platform :ios, '9.0'

target 'RETailedButtonLabel_Example' do
  pod 'RETailedButtonLabel', :path => '../'

  target 'RETailedButtonLabel_Tests' do
    inherit! :search_paths

    
  end
end
